name:  CI/CD Pipeline

on:
  push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }} 


      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag url-shortner:${{ steps.vars.outputs.sha_short }}

      - uses: actions/checkout@v3
      - name: update docker-compose.yml
        run: |
          sed -i 's/IMAGE_TAG/${{ steps.vars.outputs.sha_short }}/g' docker-compose.yml
          cp ./docker-compose.yml /home/ubuntu/docker-compose.yml
          
      - name: Deploy Application & Database 
        run: |
          docker-compose -f /home/ubuntu/docker-compose.yml up -d 




